version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    networks:
    - simpleshub-network
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    networks:
      - simpleshub-network

networks:
  simpleshub-network:
    driver: bridge